name: Build Java Maven Calculator Web App

on:
  push:
    branches: [master]
  pull_request: 
    branches: [master]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Pulls repo code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: "8"

      - name: Build with Maven
        run: mvn clean package -Dmaven.test.skip=true  

      - name: Rename WAR file to fixed name
        run: |
          WAR=$(ls -t target/calculator-*.war | head -n1)
          cp "$WAR" target/ROOT.war