name: Test Java Maven Calculator Web App

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "temurin"

      - name: Build (for tests)
        run: mvn clean package

      - name: Run Unit Tests
        run: mvn test

      - name: Run Integration Tests
        run: mvn integration-test

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/
      
      - name: Generate Code Coverage Report
        run: mvn cobertura:cobertura

      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: target/site/cobertura/
